; GAGAN CHORDIA 19BCE0788
DATA SEGMENT
    NUM1 DW 0788H
    NUM2 DW 2001H
    RES1 DW ?   
    RES2 DW ?
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE DS:DATA
    START:
    MOV AX, DATA
    MOV DS, AX
    MOV AX, NUM1 ; STORE THE FIRST NUMBER
    MOV BX, NUM2 ; STORE THE SECOND NUMBER
    MUL BX  ; MULTIPLY THEM
    MOV RES1, AX ; STORE THE VALUE
    MOV RES2, DX ; STORE THE CARRY FORWARD VALUE
    MOV AH, 4CH                           
    INT 21H
    CODE ENDS
END START