; GAGAN CHORDIA 19BCE0788
DATA SEGMENT
    NUM1 DB 19H
    NUM2 DB 02H
    RES DW ?
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE DS:DATA
    START:
    MOV AX, DATA
    MOV DS, AX
    MOV AX, 00H
    MOV BX, 00H
    MOV AL, NUM1 ; LOAD THE FIRST NUMBER
    MOV BL, NUM2 ; LOAD THE SECOND NUMBER
    MUL NUM2 ; MULTIPLY THEM
    MOV RES, AX ; STORE THE VALUE TO RES
    MOV AH, 4CH                           
    INT 21H
    CODE ENDS
END START