; GAGAN CHORDIA 19BCE0788
DATA SEGMENT
    NUM2 DW 0788H
    NUM1 DW 2001H
    RES1 DW ?   
    RES2 DW ?
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE DS:DATA
    START:
    MOV AX, DATA
    MOV DS, AX
    XOR AX, AX
    MOV AX, NUM1 ; LOAD THE FIRST NUMBER
    MOV BX, NUM2 ; LOAD THE SECOND NUMBER
    DIV BX ; DIVIDE THEM
    MOV RES1, AX ; STORE THE QUOTIENT
    MOV RES2, DX ; STORE THE BORROW PART OF QUOTIENT
    MOV AH, 4CH                           
    INT 21H
    CODE ENDS
END START