; GAGAN CHORDIA 19BCE0788
DATA SEGMENT
    NUM DW 0019H, 0788H
    SUM DW 2 DUP(0)
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
    START: 
    MOV AX, DATA
    MOV DS, AX
    MOV AX, NUM ; LOADING THE FIRST NUMBER TO THE REGISTER
    MOV BX, 0H ; IF THERE IS A CARRY BX WILL STORE THE VALUE, THUS BX IS CLEARED
    ADD AX, NUM + 2 ; SECOND NUMBER IS ADDED WITH AX
    JNC DOWN ; CHECK FOR CARRY
    INC BX ; IF THERE IS A CARRY INCREMENT BX
    DOWN: MOV SUM, AX ; STORING THE SUM
    MOV SUM + 2, BX ; ADDING/STORING CARRY TO SUM
    MOV AH, 4CH
    INT 21H
    CODE ENDS
END START