DATA SEGMENT
    NUM1 DB 88H
    NUM2 DB 19H
    DIF DB 2 DUP(0)
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
    START: MOV AX, DATA
    MOV DS, AX
    MOV AX, 00H
    MOV AL, NUM1
    MOV BL, NUM2  
    SUB AL, BL
    MOV DIF, AL
    MOV AH, 4CH
    INT 21H
CODE ENDS
END START