; GAGAN CHORDIA 19BCE0788
DATA SEGMENT
    NUM1 DB 0088H
    NUM2 DB 0019H
    DIF DB 2 DUP(0)
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
    START: 
    MOV AX, DATA
    MOV DS, AX
    MOV AX, 00H
    MOV AL, NUM1 ; LOAD FIRST NUMBER
    MOV BL, NUM2 ; LOAD SECOND NUMBER 
    SUB AL, BL ; SUBTRACT BOTH THE NUMBERS
    MOV DIF, AL
    MOV AH, 4CH
    INT 21H
    CODE ENDS
END START