; GAGAN CHORDIA 19BCE0788
DATA SEGMENT
    NUM1 DW 0019H, 0788H
    NUM2 DW 2106H, 2001H
    SUM DW 3 DUP(0)
    DATA ENDS
CODE SEGMENT
    ASSUME CS: CODE, DS: DATA
    START: 
    MOV AX, DATA    
    MOV DS, AX
    MOV AX, NUM1 ; LOAD THE FISRT NUMBER TO AX
    ADD AX, NUM2 ; ADD THE SECOND NUMBER WITH AX
    MOV SUM, AX  ; STORE THEIR SUM IN VARIABLE SUM
    MOV AX, NUM1 + 2 ; STORE THE SECOND PART OF THE FIRST NUMBER IN AX
    ADC AX, NUM2 + 2 ; ADD THE SECOND NUMBER WITH CARRY
    JNC DOWN ; CHECK FOR CARRY   
    MOV SUM + 4, 01H ; IF THERE IS A CARRY ADD IT TO THE SUM VARIABLE
    DOWN: MOV SUM + 2, AX ; STORE THE FINAL SUM
    MOV AX, 4CH
    INT 21H                                                                                              
    CODE ENDS
END START