DATA SEGMENT
    NUM1 DW 2106H, 2001H
    NUM2 DW 0019H, 0788H
    DIFF DW ?
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
    START: MOV AX, DATA
    MOV DS, AX
    MOV AX, NUM1
    SUB AX, NUM2
    MOV DIFF, AX
    MOV AX, NUM1 + 2
    SBB AX, NUM2 + 2
    MOV DIFF + 2, AX
    MOV AH, 4CH
    INT 21H
    CODE ENDS
END START