; GAGAN CHORDIA - 19BCE0788        
; SERIES TILL 10TH NUMBER IN DECIMAL : 0 1 1 2 3 5 8 13 21 34
; 34D = 22H
DATA SEGMENT
    NUM1 DW 00H    ; FIRST NUMBER OF FIBONACCI SERIES
    NUM2 DW 01H    ; SECOND NUMBER OF FIBONACCI SERIES
    LAST DW 08H    ; NUMBERS TO PRINT AFTER THE FIRST 2 NUMBERS
    RES DW ?
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE DS:DATA
    START:
    MOV AX, DATA
    MOV DS, AX
    MOV CX, LAST   ; STORING THE COUNTER VARIABLE
    REPEAT: MOV AX, NUM1
    MOV BX, NUM2
    ADD AX, BX     ; ADDING THE NUMBERS
    MOV NUM1, BX   ; SWAPPING NUMBERS
    MOV NUM2, AX
    LOOP REPEAT
    MOV RES, AX    ; STORING THE FINAL RESULT
    MOV AH, 4CH
    INT 21H
    CODE ENDS
END START
