; GAGAN CHORDIA - 19BCE0788
DATA SEGMENT
    NUM DW 0005H
    FACT DW ?
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE DS: DATA
    START:
    MOV AX, DATA
    MOV DS, AX
    MOV AX, 0001H    ; INITIALIZE AX TO 1
    MOV CX, NUM      ; KEEP COUNTER VALUE AS NUM
    REPEAT: MUL CX   ; LOOP TILL COUNTER = 0
    LOOP REPEAT
    MOV FACT, AX     ; STORE THE RESULT 5! = 120D = 78H
    MOV AH, 4CH
    INT 21H
    CODE ENDS
END START