; GAGAN CHORDIA - 19BCE0788
DATA SEGMENT
    NUM1 DW 39H  ; ASCII 9
    NUM2 DW 31H  ; ASCII 1
    RES DW ?
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
    START:
    MOV AX, DATA
    MOV DS, AX
    MOV AX, NUM1
    MOV BX, NUM2
    SBB AX, BX
    AAS ; ADJUST ASCII AFTER SUBTRACTION
    MOV RES, AX  ; STORING THE ADJUSTED ASCII VALUE
    MOV AH, 4CH
    INT 21H
    CODE ENDS
END START