; GAGAN CHORDIA - 19BCE0788
DATA SEGMENT
    NUM1 DW 31H  ; ASCII 1
    NUM2 DW 39H  ; ASCII 9
    RES DW ?
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
    START:
    MOV AX, DATA
    MOV DS, AX
    MOV AX, NUM1
    MUL NUM2
    AAM ; ADJUST ASCII AFTER MULTIPLICATION
    MOV RES, AX  ; STORING THE ADJUSTED VALUE
    MOV AH, 4CH
    INT 21H
    CODE ENDS
END START