; GAGAN CHORDIA
DATA SEGMENT
    STR DW 'GAGAN'
    LOC EQU $-STR ; ADDRESS OF THE GIVEN STRING
    RES DW 20 DUP(0)
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA  
    START:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX
    LEA SI, STR ; LOADING ADDRESS OF STR TO SOURCE INDEX
    LEA DI, RES ; LOADING ADDRESS OF RES TO DESTINATION INDEX
    MOV CX, LOC ; CREATING A COUNTER TO TRANSFER THE STRING BYTE
    CLD
    REP MOVSB   ; REPEATING IT TILL ALL BYTES FROM THE STRING ARE MOVED
    MOV AH, 4CH  
    INT 21H
    CODE ENDS
END START