; GAGAN CHORDIA
DATA SEGMENT
    STR DW 'GAGAN'
    LOC EQU $-STR
    RES DW 20 DUP(0)
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA  
    START:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX
    LEA SI, STR
    LEA DI, RES
    MOV CX, LOC
    CLD
    REP MOVSB
    MOV AH, 4CH  
    INT 21H
    CODE ENDS
END START