; GAGAN CHORDIA - 19BCE0788
DATA SEGMENT    
    ; 8255 CONFIG
    PA EQU 120H ; PORT A
    PB EQU 121H ; PORT B
    PC EQU 122H ; PORT C
    CW EQU 123H ; CONTROL WORD
    TABLE DB 8CH, 0C7H, 86H, 89H
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA 
    START:
    MOV AX, DATA
    MOV DS, AX  
    ; INTIALIZING 8255 PB AND PC AS O/P PORTS 
    MOV AL, 80H
    MOV DX, CW
    OUT DX, AL
    MOV BH, 04 ; DIGITS TO BE DISPLAYED
    LEA SI, TABLE
    ND: MOV CL, 08 ; NO OF SEGMENT BITS
    MOV AL, [SI]
    NB: ROL AL, 01
    MOV CH, AL
    MOV DX, PB  ; SEND OUT 1 BIT TO PB
    OUT DX, AL
    MOV AL, 01
    MOV DX, PC  ; SEND CLOCK PULSE TO PC
    OUT DX, AL
    DEC AL
    MOV DX, PC    
    OUT DX, AL
    DEC CL      ; SEND ALL 8 BITS
    JNZ NB
    DEC BH
    INC SI
    JNZ ND
    MOV AH, 4CH
    INT 21H
    CODE ENDS
END START